name: Deploy to PipeOps

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PipeOps CLI
        run: curl -fsSL https://raw.githubusercontent.com/PipeOpsHQ/pipeops-cli/main/install.sh | sh
      
      - name: Check available commands (debug)
        run: pipeops --help
      
      - name: Authenticate via config file
        env:
          PIPEOPS_TOKEN: "sat_ohqfkn4tsdhl5uk5jmgbolidywnzl2ak"
        run: |
          echo "{\"token\": \"$PIPEOPS_TOKEN\"}" > ~/.pipeops.json
      
      - name: Deploy to PipeOps
        run: |
          pipeops deploy pipeline \
            --project-id '7f830933-8c16-4367-bf75-5c0c88cb454a' \
            --environment production \
            --branch ${{ github.ref_name }}
    
