name: Deploy to PipeOps

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PipeOps CLI
        run: curl -fsSL https://raw.githubusercontent.com/PipeOpsHQ/pipeops-cli/main/install.sh | sh

      - name: Deploy to PipeOps
        env:
          PIPEOPS_TOKEN: "sat_ohqfkn4tsdhl5uk5jmgbolidywnzl2ak"
        run: |
          pipeops auth login --token "sat_ohqfkn4tsdhl5uk5jmgbolidywnzl2ak"
          pipeops deploy --project-id '7f830933-8c16-4367-bf75-5c0c88cb454a' --environment production --branch ${{ github.ref_name }}
      - name: Check CLI commands
        run: pipeops deploy --help
    
